export const userConstants = {

	LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
	LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',

	GET_OTHER_USER_REQUEST: 'USERS_GET_OTHER_USER_REQUEST',
	GET_OTHER_USER_SUCCESS: 'USERS_GET_OTHER_USER_SUCCESS',

	SIGNUP_PHOTO: 'USERS_SIGNUP_PHOTO',
	DELETE_PHOTO: 'USERS_DELETE_PHOTO',
	SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
	SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',

	UPDATE_REQUEST: 'USERS_UPDATE_REQUEST',
	UPDATE_SUCCESS: 'USERS_UPDATE_SUCCESS',

	EMAIL_VERIFICATION_REQUEST: 'USERS_EMAIL_VERIFICATION_REQUEST',
	EMAIL_VERIFICATION_SUCCESS: 'USERS_EMAIL_VERIFICATION_SUCCESS',

	RESETPASS_EMAIL_REQUEST: 'USERS_RESETPASS_EMAIL_REQUEST',
	RESETPASS_EMAIL_SUCCESS: 'USERS_RESETPASS_EMAIL_SUCCESS',
	RESETPASS_TOKEN_REQUEST: 'USERS_RESETPASS_TOKEN_REQUEST',
	RESETPASS_TOKEN_SUCCESS: 'USERS_RESETPASS_TOKEN_SUCCESS',

	GET_COMMENT_REQUEST: 'USERS_GET_COMMENT_REQUEST',
	GET_COMMENT_SUCCESS: 'USERS_GET_COMMENT_SUCCESS',
	POST_COMMENT_REQUEST: 'USERS_POST_COMMENT_REQUEST',
	POST_COMMENT_SUCCESS: 'USERS_POST_COMMENT_SUCCESS',

	LOGOUT: 'USERS_LOGOUT',

	GETUSER_REQUEST: 'USERS_GETUSER_REQUEST',
	GETUSER_SUCCESS: 'USERS_GETUSER_SUCCESS',
	
	//********MOVIES*************
	GENRE_REQUEST: 'USERS_GENRE_REQUEST',
	GENRE_SUCCESS: 'USERS_GENRE_SUCCESS',

	INIT_MOVIES_REQUEST: 'USERS_INIT_MOVIES_REQUEST',
	INIT_MOVIES_SUCCESS: 'USERS_INIT_MOVIES_SUCCESS',

	MOVIES_REQUEST: 'USERS_MOVIES_REQUEST',
	MOVIES_SUCCESS: 'USERS_MOVIES_SUCCESS',

	MOVIE_INFO_REQUEST: 'USERS_MOVIES_INFO_REQUEST',
	MOVIE_INFO_SUCCESS: 'USERS_MOVIES_INFO_SUCCESS',

	MOVIES_MORE_REQUEST: 'USERS_MOVIES_MORE_REQUEST',
	MOVIES_MORE_SUCCESS: 'USERS_MOVIES_MORE_SUCCESS',

	MOVIES_FILTER_SUCCESS: 'USERS_MOVIES_FILTER_SUCCESS',

	MOVIE_VIEWED_REQUEST: 'USERS_MOVIE_VIEWED_REQUEST',
	MOVIE_VIEWED_SUCCESS: 'USERS_MOVIE_VIEWED_SUCCESS',
};